packages:
  - name: agents
    environment:
      # DATABASE_URL will be substituted to the DATABASE_URL_READ_ONLY value
      # defined in App Platform's environment variable configuration.
      # NOTE: The receiving variable name does not need to match the name as
      # defined in the app / component config. This facilitates narrowly
      # scoped or overlapping values.
      AWS_SERVER_PUBLIC_KEY: "${AWS_SERVER_PUBLIC_KEY}"
      AWS_SERVER_SECRET_KEY: "${AWS_SERVER_SECRET_KEY}"
    actions:
      - name: top_subjects
        runtime: 'python:default'
